require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5

# Align the elements of a hash literal if they span more than one line.
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Check the indentation of the first argument in a method call.
Layout/IndentFirstArgument:
  EnforcedStyle: consistent

# Check the indentation of the first element in an array literal.
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

# Check the indentation of the first key in a hash literal.
Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

# Check for ambiguous regexp literals in the first argument of a method invocation without parentheses.
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Check the naming of accessor methods for get_/set_.
Naming/AccessorMethodName:
  Enabled: false

# Check the names of predicate methods.
Naming/PredicateName:
  Enabled: false

# A calculated magnitude based on number of assignments, branches, and conditions.
Metrics/AbcSize:
  Enabled: false

# Avoid long blocks with many lines.
Metrics/BlockLength:
  Enabled: false

# Avoid excessive block nesting.
Metrics/BlockNesting:
  Enabled: false

# Avoid classes longer than 100 lines of code.
Metrics/ClassLength:
  Enabled: false

# A complexity metric that is strongly correlated to the number of test cases needed to validate a method.
Metrics/CyclomaticComplexity:
  Enabled: false

# Limit lines to 80 characters.
Metrics/LineLength:
  Enabled: false

# Avoid methods longer than 10 lines of code.
Metrics/MethodLength:
  Enabled: false

# Avoid modules longer than 100 lines of code.
Metrics/ModuleLength:
  Enabled: false

# Avoid parameter lists longer than three or four parameters.
Metrics/ParameterLists:
  Enabled: false

# A complexity metric geared towards measuring complexity for a human reader.
Metrics/PerceivedComplexity:
  Enabled: false

# Use only ascii symbols in comments.
Style/AsciiComments:
  Enabled: false

# Enforce braces style around hash parameters.
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

# Do not place comments on the same line as certain keywords.
Style/CommentedKeyword:
  Enabled: false

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: false

# Put empty method definitions on a single line.
Style/EmptyMethod:
  Enabled: false

# Favor modifier if/unless usage when you have a single-line body.
Style/IfUnlessModifier:
  Enabled: false

# Add underscores to large numeric literals to improve their readability.
Style/NumericLiterals:
  Enabled: false

# Check for the use of predicate or comparison methods for numeric comparisons.
Style/NumericPredicate:
  Enabled: false

# Enforce using // or %r around regular expressions.
Style/RegexpLiteral:
  Enabled: false

# Check for unwanted commas and colons in %i/%I literals.
Style/SymbolArray:
  Enabled: false

# Favor modifier while/until usage when you have a single-line body.
Style/WhileUntilModifier:
  Enabled: false

# Use %w or %W for arrays of words.
Style/WordArray:
  Enabled: false
