# Example config for dependabot
# Move this file to .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 7
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      bundler:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
