# Example config for pull request CI
# Move this file to .github/workflows/pull_request.yml

name: pull_request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rubyproject
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Clone configuration file
        run: cp -nv "config/config.example.yml" "config/config.yml"
      - name: Migrate database
        run: |
          bundle exec rake db:migrate
          bundle exec rake db:version
      - name: Run RSpec
        run: bundle exec rake spec
      - name: Run RuboCop
        run: bundle exec rake rubocop
