mysql:
  host: '127.0.0.1'
  port: 3306
  username: username
  password: password
  database: rubyproject
telegram:
  token: 000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  user: 000000000
aws:
  access_key_id: AAAAAAAAAAAAAAAAAAAA
  secret_access_key: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
  region: eu-west-1
  bucket: mybucket
  prefix: subfolder/rubyproject/
