postgres:
  host: '127.0.0.1'
  port: 5432
  username: username
  password: password
  database: rubyproject
telegram:
  app_name: rubyproject
  token: 000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  user: 000000000
  enabled: true
aws:
  s3:
    access_key_id: AAAAAAAAAAAAAAAAAAAA
    secret_access_key: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
    region: eu-west-1
    bucket: mybucket
    prefix: subfolder/rubyproject/
  ses:
    access_key_id: AAAAAAAAAAAAAAAAAAAA
    secret_access_key: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
    region: eu-west-1
    from_name: rubyproject
    from_email: rubyproject@example.com
    to_email: myaddress@example.com
    encoding: utf-8
